# Generated by Django 5.0.6 on 2024-08-03 08:32

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GouseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_uuid', models.CharField(blank=True, max_length=200, verbose_name='user uuid')),
                ('islogginIn', models.BooleanField(blank=True, default=False)),
                ('divase', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=12, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('hostName', models.CharField(blank=True, default='web', max_length=100)),
                ('create_at', models.DateField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('userId', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('otp', models.CharField(max_length=6)),
                ('count', models.PositiveSmallIntegerField(default=0, help_text='Number of otp sent')),
                ('verify', models.BooleanField(default=False, verbose_name='is verify')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('author', models.BooleanField(blank=True, default=False, verbose_name='author')),
                ('special_user', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Special User')),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('two_step_password', models.BooleanField(default=False, help_text='is active two step password?', verbose_name='two step password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
