# Generated by Django 5.0.6 on 2024-08-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodimlar',
            name='created_at',
        ),
    ]
