# Generated by Django 5.0.6 on 2024-08-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='xodim',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
    ]
