# Generated by Django 5.0.6 on 2024-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
