# Generated by Django 5.0.6 on 2024-08-19 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_xodimlar_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
