# Generated by Django 5.0.6 on 2024-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraddress_address_alter_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_user',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
