# Generated by Django 5.0.6 on 2024-08-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_crm_user'),
        ('settings', '0009_dokon_lat_dokon_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='viloyat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar', verbose_name='Viloyat Id'),
        ),
    ]
