# Generated by Django 5.1 on 2024-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0003_alter_importproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproduct',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
