# Generated by Django 5.0.6 on 2024-10-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0004_alter_importproduct_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('articul', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
