# Generated by Django 5.1 on 2024-09-10 10:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=400)),
                ('product_name_ru', models.CharField(blank=True, max_length=400, null=True)),
                ('product_name_uz', models.CharField(blank=True, max_length=400, null=True)),
                ('material_nomer', models.BigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True)),
                ('articul', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_data', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_data_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_data_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('tavar_dagavornaya', models.BooleanField(default=False)),
                ('short_content', models.JSONField(blank=True, null=True)),
                ('short_content_ru', models.JSONField(blank=True, null=True)),
                ('short_content_uz', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('content_ru', models.JSONField(blank=True, null=True)),
                ('content_uz', models.JSONField(blank=True, null=True)),
                ('full_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('full_description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('full_description_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_video', models.FileField(blank=True, null=True, upload_to='productvideo')),
                ('deliver_date', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('serenaTrue_countFalse', models.BooleanField(default=True, editable=False)),
                ('counts', models.IntegerField(blank=True, default=0)),
                ('max_count', models.IntegerField(blank=True, default=0)),
                ('xitlar', models.BooleanField(blank=True, default=False)),
                ('news', models.BooleanField(blank=True, default=False)),
                ('banner_add', models.BooleanField(blank=True, default=False)),
                ('aksiya', models.BooleanField(blank=True, default=False)),
                ('news_title', models.CharField(blank=True, max_length=20, null=True)),
                ('news_title_ru', models.CharField(blank=True, max_length=20, null=True)),
                ('news_title_uz', models.CharField(blank=True, max_length=20, null=True)),
                ('aksiya_title', models.CharField(blank=True, max_length=20, null=True)),
                ('aksiya_title_ru', models.CharField(blank=True, max_length=20, null=True)),
                ('aksiya_title_uz', models.CharField(blank=True, max_length=20, null=True)),
                ('xitlar_title', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('available', models.BooleanField(blank=True, default=True, editable=False)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory')),
                ('super_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.supercategory')),
            ],
            options={
                'verbose_name_plural': 'Tavarlar',
                'ordering': ['pk', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.product')),
            ],
        ),
    ]
