# Generated by Django 5.0.6 on 2024-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
