# Generated by Django 5.0.6 on 2024-08-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiltersProduct',
        ),
    ]
