# Generated by Django 5.0.6 on 2024-08-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_filtersproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
    ]
