# Generated by Django 5.1 on 2024-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=400, null=True, unique=True),
        ),
    ]
