# Generated by Django 5.0.6 on 2024-08-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_product_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimage',
        ),
    ]
