# Generated by Django 5.1 on 2024-09-11 13:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
