# Generated by Django 5.0.6 on 2024-08-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
