# Generated by Django 5.0.6 on 2024-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_short_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
