# Generated by Django 5.0.6 on 2024-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['super_category', 'main_category', 'sub_category', 'articul', 'slug'], name='product_pro_super_c_5f1463_idx'),
        ),
    ]
