# Generated by Django 5.0.6 on 2024-08-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk', 'product_name'], 'verbose_name_plural': 'Tavarlar'},
        ),
    ]
