# Generated by Django 5.0.6 on 2024-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_product_pro_super_c_5f1463_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site_rts',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='site_sts',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
