# Generated by Django 5.0.6 on 2024-10-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_site_rts_alter_product_site_sts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cash_foiz',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
