# Generated by Django 5.0.6 on 2024-08-22 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('marketing', models.BooleanField(blank=True, default=False)),
                ('sotuvchi', models.BooleanField(blank=True, default=False)),
                ('content_manager', models.BooleanField(blank=True, default=False)),
                ('coll_center', models.BooleanField(blank=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('ishni_boshlash_vaqti', models.TimeField(blank=True, null=True)),
                ('ishni_bitirish_vaqti', models.TimeField(blank=True, null=True)),
                ('permision', models.ManyToManyField(blank=True, to='auth.group')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
    ]
