# Generated by Django 5.1 on 2024-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='status',
            field=models.CharField(choices=[('sts', 'site sts'), ('rts', 'site rts')], default='sts', max_length=10),
        ),
    ]
