# Generated by Django 5.0.6 on 2024-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_sites_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaCheClear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_cache', models.BooleanField(default=False)),
            ],
        ),
    ]
