# Generated by Django 5.0.6 on 2024-08-06 09:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=200, unique=True)),
                ('main_name_uz', models.CharField(max_length=200, null=True, unique=True)),
                ('main_name_ru', models.CharField(max_length=200, null=True, unique=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='categories/main/imgs/', verbose_name=' Main Category Image')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('header_add', models.BooleanField(blank=True, default=False)),
                ('main_meta', models.CharField(blank=True, max_length=200, null=True)),
                ('main_meta_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('main_meta_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('ommabob', models.BooleanField(blank=True, default=False)),
                ('main_content', models.CharField(blank=True, max_length=300, null=True)),
                ('main_content_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('main_content_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('sts_site', models.BooleanField(default=False)),
                ('rts_site', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MainCategory',
                'ordering': ['pk', 'main_name'],
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_name', models.CharField(max_length=200, unique=True)),
                ('super_name_uz', models.CharField(max_length=200, null=True, unique=True)),
                ('super_name_ru', models.CharField(max_length=200, null=True, unique=True)),
                ('category_image', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 120px X 120px', null=True, upload_to='categories/super/imgs/', verbose_name='Category Image')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('meta_name', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_content', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_content_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_content_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('seo_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('seo_content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('seo_content_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sts_site', models.BooleanField(default=False)),
                ('rts_site', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SuperCategory',
                'ordering': ['pk', 'super_name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200, unique=True)),
                ('sub_name_uz', models.CharField(max_length=200, null=True, unique=True)),
                ('sub_name_ru', models.CharField(max_length=200, null=True, unique=True)),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='categories/main/imgs/', verbose_name='Sub Category Image')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('sub_meta', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_meta_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_meta_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_content', models.CharField(blank=True, max_length=300, null=True)),
                ('sub_content_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('sub_content_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('seo_cub', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('seo_cub_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('seo_cub_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_description', models.JSONField(blank=True, null=True)),
                ('product_description_uz', models.JSONField(blank=True, null=True)),
                ('product_description_ru', models.JSONField(blank=True, null=True)),
                ('product_content', models.JSONField(blank=True, null=True)),
                ('product_content_uz', models.JSONField(blank=True, null=True)),
                ('product_content_ru', models.JSONField(blank=True, null=True)),
                ('product_filter', models.JSONField(blank=True, null=True)),
                ('product_filter_uz', models.JSONField(blank=True, null=True)),
                ('product_filter_ru', models.JSONField(blank=True, null=True)),
                ('sts_site', models.BooleanField(default=False)),
                ('rts_site', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mainCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.maincategory')),
            ],
            options={
                'verbose_name_plural': 'SubCategory',
                'ordering': ['pk', 'sub_name'],
            },
        ),
        migrations.AddField(
            model_name='maincategory',
            name='superCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.supercategory'),
        ),
        migrations.CreateModel(
            name='SuperCategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='category/images')),
                ('header_contet', models.CharField(blank=True, max_length=200, null=True)),
                ('header_contet_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('header_contet_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('supercategory_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.supercategory')),
            ],
        ),
    ]
