# Generated by Django 5.1 on 2024-09-10 10:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, verbose_name='Rating')),
                ('main_name', models.CharField(max_length=200, unique=True, verbose_name='Kategoriya uchun nom')),
                ('main_name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Kategoriya uchun nom')),
                ('main_name_uz', models.CharField(max_length=200, null=True, unique=True, verbose_name='Kategoriya uchun nom')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='categories/main/imgs/', verbose_name='Kategoriya rasm')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='category', verbose_name='Icon')),
                ('header_add', models.BooleanField(blank=True, default=False, verbose_name="Headerga qo'shish uchun status")),
                ('main_meta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('main_meta_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('main_meta_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('ommabob', models.BooleanField(blank=True, default=False, verbose_name='Ommabob Tavarlar uchun status')),
                ('main_content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kategoriya uchun  content')),
                ('main_content_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kategoriya uchun  content')),
                ('main_content_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kategoriya uchun  content')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Site chiqish uchun status')),
                ('sts_site', models.BooleanField(default=False, verbose_name='Site STS uchun status')),
                ('rts_site', models.BooleanField(default=False, verbose_name='Site RTS uchun status')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name_plural': 'Main Kategoriyalar',
                'ordering': ['pk', 'main_name'],
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, verbose_name='Rating')),
                ('super_name', models.CharField(max_length=200, unique=True, verbose_name='Asosiy Kategoriya Nomi')),
                ('super_name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Asosiy Kategoriya Nomi')),
                ('super_name_uz', models.CharField(max_length=200, null=True, unique=True, verbose_name='Asosiy Kategoriya Nomi')),
                ('category_image', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 120px X 120px', null=True, upload_to='categories/super/imgs/', verbose_name='Category Image')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True)),
                ('super_image_content', models.ImageField(blank=True, help_text='width: 1850px; height: 382px;', null=True, upload_to='category')),
                ('super_image_content_ru', models.ImageField(blank=True, help_text='width: 1850px; height: 382px;', null=True, upload_to='category')),
                ('super_image_content_uz', models.ImageField(blank=True, help_text='width: 1850px; height: 382px;', null=True, upload_to='category')),
                ('icon', models.FileField(blank=True, help_text='max_widht:50, max_height:50', null=True, upload_to='category', verbose_name='Icon')),
                ('meta_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('meta_name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('meta_name_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('meta_content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta uchun  content')),
                ('meta_content_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta uchun  content')),
                ('meta_content_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta uchun  content')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Site chiqish uchun status')),
                ('seo_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content')),
                ('seo_content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content')),
                ('seo_content_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content')),
                ('sts_site', models.BooleanField(default=False, verbose_name='Site STS uchun status')),
                ('rts_site', models.BooleanField(default=False, verbose_name='Site RTS uchun status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name_plural': 'Asosiy Kategoriyalar',
                'ordering': ['pk', 'super_name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, verbose_name='Rating')),
                ('sub_name', models.CharField(max_length=200, unique=True, verbose_name='Sub Kategoriya uchun nom')),
                ('sub_name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Sub Kategoriya uchun nom')),
                ('sub_name_uz', models.CharField(max_length=200, null=True, unique=True, verbose_name='Sub Kategoriya uchun nom')),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='categories/main/imgs/', verbose_name='Sub Kategoriya rasm')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True)),
                ('sub_meta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('sub_meta_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('sub_meta_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom')),
                ('sub_content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Kategoriya uchun  content')),
                ('sub_content_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Kategoriya uchun  content')),
                ('sub_content_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Kategoriya uchun  content')),
                ('seo_cub', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content')),
                ('seo_cub_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content')),
                ('seo_cub_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content')),
                ('product_description', models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun qiymatlar')),
                ('product_description_ru', models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun qiymatlar')),
                ('product_description_uz', models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun qiymatlar')),
                ('product_content', models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun short  qiymatlar')),
                ('product_content_ru', models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun short  qiymatlar')),
                ('product_content_uz', models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun short  qiymatlar')),
                ('sts_site', models.BooleanField(default=False, verbose_name='Site STS uchun status')),
                ('rts_site', models.BooleanField(default=False, verbose_name='Site RTS uchun status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('mainCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.maincategory', verbose_name='Main Kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Sub Kategoriyalar',
                'ordering': ['pk', 'sub_name'],
            },
        ),
        migrations.AddField(
            model_name='maincategory',
            name='superCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.supercategory', verbose_name='Asosiy Kategoriya'),
        ),
    ]
