# Generated by Django 5.0.6 on 2024-08-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='icon',
            field=models.FileField(blank=True, help_text='max_widht:50, max_height:50', null=True, upload_to='category/icon'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='super_image_content',
            field=models.ImageField(blank=True, height_field='width: 1850px; height: 382px;', null=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='super_image_content_ru',
            field=models.ImageField(blank=True, height_field='width: 1850px; height: 382px;', null=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='super_image_content_uz',
            field=models.ImageField(blank=True, height_field='width: 1850px; height: 382px;', null=True, upload_to='category'),
        ),
        migrations.DeleteModel(
            name='SuperCategoryContent',
        ),
    ]
