# Generated by Django 5.0.6 on 2024-10-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product_content',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_content_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_content_uz',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_description_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_description_uz',
        ),
    ]
