# Generated by Django 5.0.6 on 2024-10-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_subcategory_product_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
