# Generated by Django 5.0.6 on 2024-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_supercategory_icon_supercategory_super_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category/icon'),
        ),
    ]
