# Generated by Django 5.0.6 on 2024-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_maincategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='super_image_content',
            field=models.ImageField(blank=True, help_text='width: 1850px; height: 382px;', null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='super_image_content_ru',
            field=models.ImageField(blank=True, help_text='width: 1850px; height: 382px;', null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='super_image_content_uz',
            field=models.ImageField(blank=True, help_text='width: 1850px; height: 382px;', null=True, upload_to='category'),
        ),
    ]
