# Generated by Django 5.0.6 on 2024-08-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_supercategory_super_image_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='icon',
            field=models.FileField(blank=True, help_text='max_widht:50, max_height:50', null=True, upload_to='category'),
        ),
    ]
