# Generated by Django 5.0.6 on 2024-08-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_maincategory_icon_alter_supercategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True),
        ),
    ]
