# Generated by Django 5.0.6 on 2024-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_maincategory_slug_alter_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
