# Generated by Django 5.0.6 on 2024-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_maincategory_rating_subcategory_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['pk', 'main_name'], 'verbose_name_plural': 'Main Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['pk', 'sub_name'], 'verbose_name_plural': 'Sub Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ['pk', 'super_name'], 'verbose_name_plural': 'Asosiy Kategoriyalar'},
        ),
    ]
