# Generated by Django 5.0.6 on 2024-08-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_maincategory_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product_filter',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_filter_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_filter_uz',
        ),
    ]
