# Generated by Django 5.0.6 on 2024-08-23 13:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_subcategory_product_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='header_add',
            field=models.BooleanField(blank=True, default=False, verbose_name="Headerga qo'shish uchun status"),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_content',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kategoriya uchun  content'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_content_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kategoriya uchun  content'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_content_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kategoriya uchun  content'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/main/imgs/', verbose_name='Kategoriya rasm'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_meta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_meta_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_meta_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Kategoriya uchun nom'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Kategoriya uchun nom'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_name_uz',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Kategoriya uchun nom'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='ommabob',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ommabob Tavarlar uchun status'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='rts_site',
            field=models.BooleanField(default=False, verbose_name='Site RTS uchun status'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Site chiqish uchun status'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='sts_site',
            field=models.BooleanField(default=False, verbose_name='Site STS uchun status'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='superCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.supercategory', verbose_name='Asosiy Kategoriya'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='mainCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.maincategory', verbose_name='Main Kategoriya'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_content',
            field=models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun short  qiymatlar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_content_ru',
            field=models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun short  qiymatlar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_content_uz',
            field=models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun short  qiymatlar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_description',
            field=models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun qiymatlar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_description_ru',
            field=models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun qiymatlar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_description_uz',
            field=models.JSONField(blank=True, null=True, verbose_name='Tegishli tavarlar uchun qiymatlar'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rts_site',
            field=models.BooleanField(default=False, verbose_name='Site RTS uchun status'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='seo_cub',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='seo_cub_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='seo_cub_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sts_site',
            field=models.BooleanField(default=False, verbose_name='Site STS uchun status'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_content',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Kategoriya uchun  content'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_content_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Kategoriya uchun  content'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_content_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Kategoriya uchun  content'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/main/imgs/', verbose_name='Sub Kategoriya rasm'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_meta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_meta_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_meta_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Sub Kategoriya uchun nom'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Sub Kategoriya uchun nom'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_name_uz',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Sub Kategoriya uchun nom'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='icon',
            field=models.FileField(blank=True, help_text='max_widht:50, max_height:50', null=True, upload_to='category', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='meta_content',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta uchun  content'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='meta_content_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta uchun  content'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='meta_content_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta uchun  content'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='meta_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='meta_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='meta_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta uchun nom'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='rts_site',
            field=models.BooleanField(default=False, verbose_name='Site RTS uchun status'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='seo_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='seo_content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='seo_content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO uchun  Content'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Site chiqish uchun status'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='sts_site',
            field=models.BooleanField(default=False, verbose_name='Site STS uchun status'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='super_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Asosiy Kategoriya Nomi'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='super_name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Asosiy Kategoriya Nomi'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='super_name_uz',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Asosiy Kategoriya Nomi'),
        ),
    ]
