# Generated by Django 5.0.6 on 2024-08-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloghome_text_ru_bloghome_text_uz_bloghome_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Blog Category'},
        ),
        migrations.AlterModelOptions(
            name='bloghome',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Home page blog'},
        ),
        migrations.AlterModelOptions(
            name='blogitem',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Blog Item'},
        ),
        migrations.RenameField(
            model_name='blogitem',
            old_name='category',
            new_name='blogcategory',
        ),
    ]
