# Generated by Django 5.0.6 on 2024-08-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcategory_options_alter_bloghome_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'blogcategory'},
        ),
    ]
