# Generated by Django 5.0.6 on 2024-08-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogitem',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'blogitem'},
        ),
    ]
