# Generated by Django 5.0.6 on 2024-08-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
