# Generated by Django 5.0.6 on 2024-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategory_title_ru_blogcategory_title_uz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Blog Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='bloghome',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Asosiy oyna uchun Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='blogitem',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Blog Taglar'},
        ),
    ]
