# Generated by Django 5.0.6 on 2024-08-22 10:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcategory_options_alter_bloghome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogcategory', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='blog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Home sayti blog uchun malumot'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Home sayti blog uchun malumot'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='text_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Home sayti blog uchun malumot'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Home sayti blog nomi'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Home sayti blog nomi'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='title_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Home sayti blog nomi'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilanish vaqti'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='blogcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Blog uchun malumot'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog uchun malumot'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog uchun malumot'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogitems', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Taglar'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog nomi'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog nomi'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog nomi'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilanish vaqti'),
        ),
    ]
