# Generated by Django 5.1 on 2024-09-10 10:07

import ckeditor.fields
import django.db.models.deletion
import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'page card',
                'verbose_name_plural': 'page cards',
                'ordering': ['pk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('zakas_summa', models.BigIntegerField(blank=True)),
                ('dastafka_summa', models.BigIntegerField(blank=True)),
                ('teskor_buyurtma', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berish Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='Dokon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dokonlar')),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Dokon',
                'verbose_name_plural': 'Dokonlar',
                'ordering': ['name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='MuddatliTolovxizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='tolov')),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('kredit_muddat_foiz', models.JSONField(blank=True, default=settings.models.muddat_tolov_fn)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depozit_tolov', models.BooleanField(blank=True, default=False)),
                ('firma', models.BooleanField(blank=True, default=False, verbose_name='Firma orqali Mahsulot buyurtma')),
                ('cashback_tolov', models.BooleanField(blank=True, default=False)),
                ('tolov_online', models.BooleanField(blank=True, default=True)),
                ('nds', models.PositiveIntegerField(blank=True, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('doller', models.IntegerField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyurtma Sozlama',
                'verbose_name_plural': 'Buyurtma Sozlamalar',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='payment')),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Tolov',
                'verbose_name_plural': 'Tolovlar',
                'ordering': ['pk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServisPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavchi')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Sarlavchi')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Sarlavchi')),
                ('image', models.ImageField(upload_to='servis_page/', verbose_name='image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Sarlavchi matn')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Sarlavchi matn')),
                ('content_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Sarlavchi matn')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shaharlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('dastafka', models.BooleanField(blank=True, default=True)),
                ('zakas_summa', models.PositiveIntegerField(blank=True, null=True)),
                ('summa', models.PositiveIntegerField(blank=True, null=True)),
                ('teskor_buyurtma', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=100)),
                ('page_name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('page_name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'content page',
                'ordering': ['pk', 'page_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('icon', models.FileField(blank=True, upload_to='socialnetwork')),
                ('link', models.URLField(blank=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('site_data', models.CharField(blank=True, editable=False, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Ijtimoiy Tarmoq',
                'verbose_name_plural': 'Ijtimoiy Tarmoqlar',
                'ordering': ['pk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashBackSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_foiz', models.PositiveIntegerField(blank=True, null=True, verbose_name='cashback foizi')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_tavar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory', verbose_name='Tavar turi')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='BItta Tovar uchun cashback')),
            ],
            options={
                'verbose_name': 'Cashback Setting',
                'verbose_name_plural': 'Cashback Settings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=5)),
                ('mainCategory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory')),
            ],
            options={
                'verbose_name': 'Tavar Soni',
                'verbose_name_plural': 'Tavarlar Soni',
                'ordering': ['pk', 'mainCategory'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='malumot/image')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('card', models.ManyToManyField(blank=True, to='settings.cardgril')),
                ('pages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.sitepage')),
            ],
            options={
                'verbose_name_plural': 'Page',
                'ordering': ['pk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/images')),
                ('icon', models.FileField(blank=True, null=True, upload_to='logo/images')),
                ('site_name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('site_stopped', models.BooleanField(blank=True, default=False)),
                ('open_time', models.CharField(blank=True, max_length=30, null=True)),
                ('close_time', models.CharField(blank=True, max_length=30, null=True)),
                ('date_week', models.CharField(blank=True, max_length=50, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='logo/image')),
                ('socialnetwork', models.ManyToManyField(blank=True, to='settings.socialnetwork')),
            ],
            options={
                'verbose_name': 'Site Sozlama',
                'verbose_name_plural': 'Site Sozlamalar',
                'ordering': ['pk', 'site_name'],
            },
        ),
        migrations.CreateModel(
            name='TolovUsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='tolov')),
                ('content', models.TextField(blank=True, null=True)),
                ('content_ru', models.TextField(blank=True, null=True)),
                ('content_uz', models.TextField(blank=True, null=True)),
                ('firma', models.BooleanField(blank=True, default=False, editable=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('payment_methods', models.ManyToManyField(blank=True, to='settings.paymentmethod')),
            ],
            options={
                'verbose_name': 'Tolov usul',
                'verbose_name_plural': 'Tolov Usullar',
                'ordering': ['pk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tumanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('viloyat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
    ]
