# Generated by Django 5.0.6 on 2024-08-06 09:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardGril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('zakas_summa', models.BigIntegerField(blank=True)),
                ('dastafka_summa', models.BigIntegerField(blank=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='payment')),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=100)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/images')),
                ('icon', models.ImageField(blank=True, upload_to='logo/images')),
                ('site_name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('site_stopped', models.BooleanField(blank=True, default=False)),
                ('open_time', models.CharField(blank=True, max_length=30, null=True)),
                ('close_time', models.CharField(blank=True, max_length=30, null=True)),
                ('date_week', models.CharField(blank=True, max_length=50, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depozit_tolov', models.BooleanField(blank=True, default=False)),
                ('cashback_tolov', models.BooleanField(blank=True, default=False)),
                ('tolov_online', models.BooleanField(blank=True, default=True)),
                ('nds', models.PositiveIntegerField(blank=True, null=True)),
                ('date_update', models.DateField(blank=True, null=True)),
                ('cource_valyuta', models.PositiveIntegerField(blank=True, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('tolov_usullar', models.ManyToManyField(blank=True, to='settings.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='malumot/image')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('card', models.ManyToManyField(blank=True, to='settings.cardgril')),
                ('pages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.sitepage')),
            ],
            options={
                'verbose_name_plural': 'Page',
                'ordering': ['pk', 'title'],
            },
        ),
    ]
