# Generated by Django 5.0.6 on 2024-08-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
