# Generated by Django 5.0.6 on 2024-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokon',
            name='site_rts',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dokon',
            name='site_sts',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
