# Generated by Django 5.0.6 on 2024-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolovusullar',
            name='nasiya',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tolovusullar',
            name='operator',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
