# Generated by Django 5.0.6 on 2024-08-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitepage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='page_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='page_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
