# Generated by Django 5.0.6 on 2024-08-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_dokon_site_rts_dokon_site_sts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuddatliTOlov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Tolov nomi')),
                ('key', models.CharField(blank=True, max_length=200, verbose_name='Banking bank_key')),
                ('foiz', models.PositiveIntegerField(blank=True, null=True, verbose_name='Foiz')),
                ('logo', models.FileField(blank=True, upload_to='mudatli_tolov')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Muddatli Tolov',
                'verbose_name_plural': 'Muddatli Tololar',
                'ordering': ['pk', 'name'],
                'unique_together': {('name', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OylikSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('muddat_tolov', models.ManyToManyField(blank=True, to='settings.muddatlitolov')),
            ],
            options={
                'verbose_name': 'Oylik Sozlama',
                'verbose_name_plural': 'Oylik Sozlamalar',
                'ordering': ['pk', 'name'],
            },
        ),
    ]
