# Generated by Django 5.0.6 on 2024-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_muddatlitolov_oyliksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyliksettings',
            name='oy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
