# Generated by Django 5.0.6 on 2024-08-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_sitepage_page_name_ru_sitepage_page_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('icon', models.FileField(blank=True, upload_to='socialnetwork')),
                ('link', models.URLField(blank=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('site_data', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='telegram',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='socialnetwork',
            field=models.ManyToManyField(blank=True, to='settings.socialnetwork'),
        ),
    ]
