# Generated by Django 5.0.6 on 2024-08-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_oyliksettings_oy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oyliksettings',
            name='muddat_tolov',
        ),
        migrations.DeleteModel(
            name='MuddatliTOlov',
        ),
        migrations.DeleteModel(
            name='OylikSettings',
        ),
    ]
