# Generated by Django 5.0.6 on 2024-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_socialnetwork_remove_sitesettings_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='socialnetwork',
            field=models.ManyToManyField(blank=True, editable=False, to='settings.socialnetwork'),
        ),
    ]
