# Generated by Django 5.0.6 on 2024-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_sitesettings_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='socialnetwork',
            field=models.ManyToManyField(blank=True, to='settings.socialnetwork'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='site_data',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
