# Generated by Django 5.0.6 on 2024-08-25 15:21

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_oyliksettings_muddat_tolov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuddatliTolovxizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='tolov')),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('kredit_muddat_foiz', models.JSONField(blank=True, default=settings.models.muddat_tolov_fn)),
            ],
        ),
    ]
