# Generated by Django 5.0.6 on 2024-08-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_muddatlitolovxizmatlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaharlar',
            name='teskor_buyurtma',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='shaharlar',
            name='zakas_summa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
