# Generated by Django 5.0.6 on 2024-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_sitesettings_socialnetwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='icon',
            field=models.FileField(blank=True, upload_to='logo/images'),
        ),
    ]
