# Generated by Django 5.0.6 on 2024-08-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_maincategory_icon'),
        ('settings', '0007_alter_sitesettings_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/image'),
        ),
        migrations.CreateModel(
            name='CountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=5)),
                ('mainCategory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory')),
            ],
        ),
    ]
