# Generated by Django 5.0.6 on 2024-08-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_maincategory_created_and_more'),
        ('product', '0011_alter_product_options'),
        ('settings', '0007_shaharlar_teskor_buyurtma_shaharlar_zakas_summa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBackSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_foiz', models.PositiveIntegerField(blank=True, null=True, verbose_name='cashback foizi')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_tavar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory', verbose_name='Tavar turi')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='BIttiy Tovar uchun cashback')),
            ],
            options={
                'verbose_name': 'Cashback Setting',
                'verbose_name_plural': 'Cashback Settings',
                'ordering': ['id'],
            },
        ),
    ]
