# Generated by Django 5.0.6 on 2024-08-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_sitesettings_footer_logo_countsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='logo/images'),
        ),
    ]
