# Generated by Django 5.0.6 on 2024-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_cashbacksetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokon',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokon',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
