# Generated by Django 5.1 on 2024-09-03 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_options'),
        ('settings', '0009_dokon_lat_dokon_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbacksetting',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='BItta Tovar uchun cashback'),
        ),
    ]
