# Generated by Django 5.0.6 on 2024-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_sitesettings_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersetting',
            name='doller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
