# Generated by Django 5.1 on 2024-09-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_cashbacksetting_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolovusullar',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tolovusullar',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tolovusullar',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tolovusullar',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
