# Generated by Django 5.0.6 on 2024-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_dokon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolovUsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('icon', models.FileField(blank=True, null=True, upload_to='tolov')),
                ('content', models.TextField(blank=True, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
