# Generated by Django 5.1 on 2024-09-08 12:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_tolovusullar_content_ru_tolovusullar_content_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavchi')),
                ('image', models.ImageField(upload_to='servis_page/', verbose_name='image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Sarlavchi matn')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
