# Generated by Django 5.0.6 on 2024-08-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_tolovusullar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaharlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('dastafka', models.BooleanField(blank=True, default=True)),
                ('summa', models.PositiveIntegerField(blank=True, null=True)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cardgril',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'page card', 'verbose_name_plural': 'page cards'},
        ),
        migrations.AlterModelOptions(
            name='countsettings',
            options={'ordering': ['pk', 'mainCategory'], 'verbose_name': 'Tavar Soni', 'verbose_name_plural': 'Tavarlar Soni'},
        ),
        migrations.AlterModelOptions(
            name='deliveryservice',
            options={'verbose_name': 'Yetkazib berish', 'verbose_name_plural': 'Yetkazib berish Sozlamalar'},
        ),
        migrations.AlterModelOptions(
            name='dokon',
            options={'ordering': ['name', 'phone'], 'verbose_name': 'Dokon', 'verbose_name_plural': 'Dokonlar'},
        ),
        migrations.AlterModelOptions(
            name='ordersetting',
            options={'ordering': ['pk'], 'verbose_name': 'Buyurtma Sozlama', 'verbose_name_plural': 'Buyurtma Sozlamalar'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['pk', 'name'], 'verbose_name': 'Tolov', 'verbose_name_plural': 'Tolovlar'},
        ),
        migrations.AlterModelOptions(
            name='sitepage',
            options={'ordering': ['pk', 'page_name'], 'verbose_name_plural': 'content page'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['pk', 'site_name'], 'verbose_name': 'Site Sozlama', 'verbose_name_plural': 'Site Sozlamalar'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['pk', 'name'], 'verbose_name': 'Ijtimoiy Tarmoq', 'verbose_name_plural': 'Ijtimoiy Tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='tolovusullar',
            options={'ordering': ['pk', 'name'], 'verbose_name': 'Tolov usul', 'verbose_name_plural': 'Tolov Usullar'},
        ),
        migrations.RemoveField(
            model_name='ordersetting',
            name='cource_valyuta',
        ),
        migrations.RemoveField(
            model_name='ordersetting',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='ordersetting',
            name='tolov_usullar',
        ),
        migrations.AddField(
            model_name='ordersetting',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tolovusullar',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='settings.paymentmethod'),
        ),
        migrations.CreateModel(
            name='Tumanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('viloyat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
    ]
