# Generated by Django 5.1 on 2024-09-08 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_servispage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servispage',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Sarlavchi matn'),
        ),
        migrations.AddField(
            model_name='servispage',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Sarlavchi matn'),
        ),
        migrations.AddField(
            model_name='servispage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavchi'),
        ),
        migrations.AddField(
            model_name='servispage',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavchi'),
        ),
    ]
