# Generated by Django 5.0.6 on 2024-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_shaharlar_alter_cardgril_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersetting',
            name='firma',
            field=models.BooleanField(blank=True, default=False, verbose_name='Firma orqali Mahsulot buyurtma'),
        ),
        migrations.AddField(
            model_name='tolovusullar',
            name='firma',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='tolovusullar',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
