# Generated by Django 5.0.6 on 2024-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_ordersetting_firma_tolovusullar_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservice',
            name='teskor_buyurtma',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='deliveryservice',
            name='teskor_buyurtma_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
