# Generated by Django 5.0.6 on 2024-08-29 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackKard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.PositiveBigIntegerField(blank=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('balance', models.PositiveIntegerField(blank=True, default=0)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_locked', models.BooleanField(blank=True, default=False)),
                ('hisobot', models.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('site_sts', models.BooleanField(blank=True, default=True)),
                ('site_rts', models.BooleanField(blank=True, default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cashback Kardlar',
                'ordering': ['id'],
            },
        ),
    ]
