# Generated by Django 5.0.6 on 2024-08-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackkard',
            name='site_rts',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cashbackkard',
            name='site_sts',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
