# Generated by Django 5.0.6 on 2024-09-21 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('familya', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('xodim_rasmi', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('ish_joyi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.DateField(auto_now_add=True, verbose_name='Kun')),
                ('check_in', models.CharField(blank=True, max_length=10, null=True, verbose_name='kelgan vaqt')),
                ('check_out', models.CharField(blank=True, max_length=10, null=True, verbose_name='ketgan vaqt')),
                ('latitude', models.FloatField(blank=True, editable=False, null=True)),
                ('longitude', models.FloatField(blank=True, editable=False, null=True)),
                ('endlatitude', models.FloatField(blank=True, editable=False, null=True)),
                ('endlongitude', models.FloatField(blank=True, editable=False, null=True)),
                ('reason_for_absence', models.CharField(blank=True, max_length=255, null=True, verbose_name='xodim xabari')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.employee', verbose_name='xodim')),
            ],
        ),
    ]
