# Generated by Django 5.0.6 on 2024-08-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='banner/images')),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to='banner/images')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='banner/images')),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Banner',
                'ordering': ['pk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='homePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis', models.BooleanField(blank=True, default=False)),
                ('ustanofka', models.BooleanField(blank=True, default=False)),
                ('maqola', models.BooleanField(blank=True, default=False)),
                ('yetkazib_berish', models.BooleanField(blank=True, default=False)),
                ('ads', models.BooleanField(blank=True, default=False)),
                ('mobile_app', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(blank=True, help_text='home page nechinchi orinda chiqsin', null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('news', models.BooleanField(blank=True, default=False)),
                ('banner_add', models.BooleanField(blank=True, default=False)),
                ('aksiya', models.BooleanField(blank=True, default=False)),
                ('xitlar', models.BooleanField(blank=True, default=False)),
                ('mainCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory')),
            ],
            options={
                'verbose_name_plural': 'homepageCategory',
                'ordering': ['pk', 'title', 'top'],
            },
        ),
    ]
