# Generated by Django 5.1 on 2024-09-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Banner uchun nom')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner uchun nom')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner uchun nom')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('url', models.URLField(blank=True, verbose_name='URL Linki')),
                ('image', models.ImageField(blank=True, upload_to='banner/images', verbose_name='Rasim')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='banner/images', verbose_name='Rasim')),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to='banner/images', verbose_name='Rasim')),
                ('site_sts', models.BooleanField(blank=True, default=False, verbose_name='Site STS')),
                ('site_rts', models.BooleanField(blank=True, default=False, verbose_name='Site RTS')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Home Banner',
                'ordering': ['pk', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(blank=True, help_text='home page nechinchi orinda chiqsin', null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/images', verbose_name='Rasim')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Linki')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('site_sts', models.BooleanField(blank=True, default=False, verbose_name='Site STS')),
                ('site_rts', models.BooleanField(blank=True, default=False, verbose_name='Site RTS')),
                ('news', models.BooleanField(blank=True, default=False, verbose_name="Yangi Tavarlar ro'yxati")),
                ('banner_add', models.BooleanField(blank=True, default=False, verbose_name="Banner Tavarlar ro'yxati")),
                ('aksiya', models.BooleanField(blank=True, default=False, verbose_name="Aksiya Tavarlar ro'yxati")),
                ('xitlar', models.BooleanField(blank=True, default=False, verbose_name="Xitlar ro'yxati")),
                ('mainCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory', verbose_name='Kategoriya tanlang')),
            ],
            options={
                'verbose_name_plural': 'Home Page Category',
                'ordering': ['pk', 'title', 'top'],
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='minicard/images')),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='status')),
                ('homepagecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardimage', to='home.homepagecategory')),
            ],
        ),
    ]
