# Generated by Django 5.0.6 on 2024-10-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
