# Generated by Django 5.0.6 on 2024-08-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/images')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('page_choise', models.CharField(blank=True, choices=[('home', 'home'), ('about', 'about'), ('delivery', 'delivery'), ('payment', 'payment'), ('contact', 'contact'), ('faq', 'faq'), ('terms', 'terms'), ('privacy', 'privacy')], max_length=200)),
            ],
        ),
    ]
