# Generated by Django 5.0.6 on 2024-10-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_cloudflare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
