# Generated by Django 5.0.6 on 2024-08-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_choise',
        ),
    ]
