# Generated by Django 5.0.6 on 2024-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_aboutpage_page_choise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='homePage',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['pk', 'title'], 'verbose_name_plural': 'Home Banner'},
        ),
        migrations.AlterModelOptions(
            name='homepagecategory',
            options={'ordering': ['pk', 'title', 'top'], 'verbose_name_plural': 'Home Page Category'},
        ),
    ]
