# Generated by Django 5.0.6 on 2024-08-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_maincategory_created_and_more'),
        ('home', '0005_delete_aboutpage_delete_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banner/images', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='banner/images', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='banner/images', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='site_rts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Site RTS'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='site_sts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Site STS'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner uchun nom'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner uchun nom'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner uchun nom'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL Linki'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='aksiya',
            field=models.BooleanField(blank=True, default=False, verbose_name="Aksiya Tavarlar ro'yxati"),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='banner_add',
            field=models.BooleanField(blank=True, default=False, verbose_name="Banner Tavarlar ro'yxati"),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/images', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Linki'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='mainCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory', verbose_name='Kategoriya tanlang'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='news',
            field=models.BooleanField(blank=True, default=False, verbose_name="Yangi Tavarlar ro'yxati"),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='site_rts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Site RTS'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='site_sts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Site STS'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='homepagecategory',
            name='xitlar',
            field=models.BooleanField(blank=True, default=False, verbose_name="Xitlar ro'yxati"),
        ),
    ]
