# Generated by Django 5.1 on 2024-09-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_banner_category_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='minicard/images')),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='status')),
                ('homepagecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardimage', to='home.homepagecategory')),
            ],
        ),
    ]
