# Generated by Django 5.0.6 on 2024-09-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bground_image', models.ImageField(upload_to='about_servis_images/')),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_servis_images/')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JopServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=200)),
                ('header_title_text', models.TextField(max_length=200)),
                ('bground_image', models.ImageField(blank=True, null=True, upload_to='jop_servis_images/')),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KomandaServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='comanda', max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('bground_image', models.ImageField(blank=True, null=True, upload_to='komanda_servis_images/')),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KontaktServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LisenceServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('bground_image', models.ImageField(blank=True, null=True, upload_to='lisence_servis_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PriceServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('bground_image', models.ImageField(blank=True, null=True, upload_to='price_servis_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UstanofkaServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('bground_image', models.ImageField(blank=True, null=True, upload_to='ustanofka_servis_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_servis_images/')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='servis.categoryservis')),
            ],
        ),
        migrations.CreateModel(
            name='AboutServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('image', models.FileField(blank=True, null=True, upload_to='about_servis_images/')),
                ('jopservis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.jopservis')),
            ],
        ),
        migrations.CreateModel(
            name='JopServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='jop_servis_images/')),
                ('jopservis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.jopservis')),
            ],
        ),
        migrations.CreateModel(
            name='KomandaServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='komanda_servis_images/')),
                ('yil', models.PositiveIntegerField(blank=True, default=3)),
                ('komandaservis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.komandaservis')),
            ],
        ),
        migrations.CreateModel(
            name='LisenceServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='lisence_servis_images/')),
                ('lisenceservis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.lisenceservis')),
            ],
        ),
        migrations.CreateModel(
            name='PriceServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(blank=True)),
                ('priceservis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.priceservis')),
            ],
        ),
        migrations.CreateModel(
            name='UstanofkaServisCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_jop', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('problem', models.TextField(blank=True, max_length=500, null=True)),
                ('solution', models.TextField(blank=True, max_length=500, null=True)),
                ('jopservis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.ustanofkaservis')),
            ],
        ),
    ]
