# Generated by Django 5.0.6 on 2024-09-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutserviscard',
            name='jopservis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aboutserviscards', to='servis.aboutservis'),
        ),
        migrations.AlterField(
            model_name='jopserviscard',
            name='jopservis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jopserviscards', to='servis.jopservis'),
        ),
        migrations.AlterField(
            model_name='komandaserviscard',
            name='komandaservis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komandaserviscard', to='servis.komandaservis'),
        ),
        migrations.AlterField(
            model_name='lisenceserviscard',
            name='lisenceservis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lisenceserviscards', to='servis.lisenceservis'),
        ),
        migrations.AlterField(
            model_name='priceserviscard',
            name='priceservis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceserviscards', to='servis.priceservis'),
        ),
        migrations.AlterField(
            model_name='ustanofkaserviscard',
            name='jopservis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ustanofkaserviscards', to='servis.ustanofkaservis'),
        ),
    ]
