# Generated by Django 5.0.6 on 2024-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0002_alter_aboutserviscard_jopservis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceservis',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='priceservis',
            name='price',
        ),
        migrations.AddField(
            model_name='priceserviscard',
            name='arzonlashgan_narx',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceserviscard',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='priceserviscard',
            name='narx',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
