# Generated by Django 5.0.6 on 2024-09-24 12:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0003_remove_priceservis_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceserviscard',
            name='count',
        ),
        migrations.RemoveField(
            model_name='priceserviscard',
            name='product_name',
        ),
        migrations.AddField(
            model_name='priceserviscard',
            name='product_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
