# Generated by Django 5.0.6 on 2024-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0004_remove_priceserviscard_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceserviscard',
            name='product_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
