# Generated by Django 5.0.6 on 2024-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0005_alter_priceserviscard_product_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryservis',
            name='link',
        ),
        migrations.AddField(
            model_name='categoryserviscard',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
