# Generated by Django 5.0.6 on 2024-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0006_remove_categoryservis_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavolJavobServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=500)),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
