# Generated by Django 5.0.6 on 2024-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0007_savoljavobservis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContentServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
