# Generated by Django 5.0.6 on 2024-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0008_contactcontentservis'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontentservis',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactcontentservis',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactcontentservis',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactcontentservis',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
