# Generated by Django 5.0.6 on 2024-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0009_contactcontentservis_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontentservis',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
