# Generated by Django 5.0.6 on 2024-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0010_contactcontentservis_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontaktservis',
            name='name',
            field=models.CharField(default='gost', max_length=200),
        ),
    ]
