# Generated by Django 5.0.6 on 2024-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0011_alter_kontaktservis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktservis',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
