# Generated by Django 5.0.6 on 2024-09-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0013_productserviscard_priceserviscard_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceserviscard',
            name='product_content',
        ),
    ]
