# Generated by Django 5.1 on 2024-09-10 10:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        ('product', '__first__'),
        ('settings', '__first__'),
        ('xodimlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(blank=True, max_length=30)),
                ('telefon', models.CharField(blank=True, max_length=25)),
                ('tex', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('summa', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_summa', models.PositiveBigIntegerField(blank=True, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('barcha_tavarlar', models.BooleanField(blank=True, default=False)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupon', to='ordersts.cupon')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaBuyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(blank=True, max_length=255, verbose_name='Firma nomi')),
                ('buyurtma_raqami', models.IntegerField(blank=True, unique=True, verbose_name='Buyurtma raqami')),
                ('inn_nomer', models.CharField(blank=True, max_length=12, null=True, verbose_name='INN nomer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('shartnoma_file', models.FileField(blank=True, null=True, upload_to='shartnoma/', verbose_name='Sharhnoma file')),
                ('shartnoma_status', models.BooleanField(default=False, verbose_name='Sharhnoma statusi')),
                ('site_sts', models.BooleanField(blank=True, default=False, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=False, verbose_name='RTS SITE')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='Soni')),
                ('serena', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Mahsulot serena nomerlari')),
                ('zakas_id', models.IntegerField(blank=True, null=True)),
                ('mahsul0t_narxi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahsulot narxi')),
                ('site_sts', models.BooleanField(blank=True, default=True, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=True, verbose_name='RTS SITE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='Mahsulotlar')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name_plural': 'Savdo qilingan mahsulotlar',
                'ordering': ['pk', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VazvratProdcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_narxi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahsulot narxi')),
                ('serena', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Mahsulot serena nomerlar')),
                ('zakas_id', models.IntegerField(blank=True, null=True, verbose_name='Buyurtma raqami')),
                ('counts', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('site_sts', models.BooleanField(blank=True, default=True, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=True, verbose_name='RTS SITE')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Mahsulot ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name_plural': 'Vazvrat qilingan mahsulotlar',
                'ordering': ['pk', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetkazish', models.DateField(blank=True, null=True, verbose_name='Yetkazish sanasi')),
                ('zakas_id', models.IntegerField(blank=True, unique=True, verbose_name='Buyurtma raqami')),
                ('cashback', models.FloatField(blank=True, null=True, verbose_name='Cashback  yechgan summa')),
                ('tushadigan_cash_summa', models.FloatField(blank=True, editable=False, null=True, verbose_name='Tushadigan cash summasi')),
                ('depozit', models.FloatField(blank=True, null=True, verbose_name='Depozit yechgan summasi')),
                ('status', models.CharField(choices=[('pending', "Yig'ilyapti"), ('processing', 'Yetkazilyapti'), ('shipped', 'Yetkazildi'), ('delivered', 'Xaridorga berildi'), ('cencel', 'Bekor Qilindi')], default='pending', max_length=10, verbose_name='Buyurtma statusi')),
                ('qishloq', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qishloq')),
                ('uy_nomer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Uy nomer')),
                ('dastafka_summa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dastafka summasi')),
                ('teskor_buyurtma', models.BooleanField(blank=True, default=False)),
                ('total_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Buyurtma narxi')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Buyurtma bekor qilingan natija')),
                ('site_sts', models.BooleanField(blank=True, default=False, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=False, verbose_name='RTS SITE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('is_finished', models.BooleanField(blank=True, default=False, verbose_name='Buyurtma tolov statusi')),
                ('cencel', models.BooleanField(blank=True, default=False, verbose_name='Buyurtma bekor qilinganmi')),
                ('order_close', models.BooleanField(blank=True, default=False, verbose_name='Buyurtma Yopish')),
                ('promocod', models.CharField(blank=True, max_length=20, null=True)),
                ('firma_buyurtma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersts.firmabuyurtma', verbose_name='Firma buyurtma')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.paymentmethod', verbose_name="Qanday to'lov qilish")),
                ('punkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manzil', to='settings.dokon', verbose_name=' Yetkazib beriladigan dokon Manzil')),
                ('shahar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar', verbose_name='Shahar')),
                ('tolov_usullar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tolovusullar', verbose_name="To'lov usullari")),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tumanlar', verbose_name='Tuman')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma Bergan Foydalanuvchi')),
                ('xodim', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xodimlar.xodim', verbose_name='Xodim')),
                ('order_items', models.ManyToManyField(blank=True, to='ordersts.orderitem', verbose_name='Savdo qilingan mahsulotlar')),
                ('vazvrat_product', models.ManyToManyField(blank=True, to='ordersts.vazvratprodcut', verbose_name='Qaytarilgan Mahsulotlar')),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at', 'zakas_id'],
            },
        ),
    ]
