# Generated by Django 5.0.6 on 2024-08-22 12:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_alter_product_options'),
        ('settings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='Soni')),
                ('serena', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Mahsulot serena nomerlari')),
                ('site_sts', models.BooleanField(blank=True, default=True, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=True, verbose_name='RTS SITE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='Mahsulotlar')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name_plural': 'Savdo qilingan mahsulotlar',
                'ordering': ['pk', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VazvratProdcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serena', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Mahsulot serena nomerlar')),
                ('counts', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Mahsulot ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name_plural': 'Vazvrat qilingan mahsulotlar',
                'ordering': ['pk', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetkazish', models.DateField(blank=True, null=True, verbose_name='Yetkazish sanasi')),
                ('zakas_id', models.IntegerField(blank=True, unique=True, verbose_name='Buyurtma raqami')),
                ('cashback', models.FloatField(blank=True, null=True, verbose_name='Cashback  yechgan summa')),
                ('depozit', models.FloatField(blank=True, null=True, verbose_name='Depozit yechgan summasi')),
                ('status', models.CharField(choices=[('pending', "Yig'ilyapti"), ('processing', 'Yetkazilyapti'), ('shipped', 'Yetkazildi'), ('delivered', 'Xaridorga berildi')], default='pending', max_length=10, verbose_name='Buyurtma statusi')),
                ('qishloq', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qishloq')),
                ('uy_nomer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Uy nomer')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Buyurtma narxi')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Buyurtma uchun admin  xabarlari')),
                ('site_sts', models.BooleanField(blank=True, default=False, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=False, verbose_name='RTS SITE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('is_finished', models.BooleanField(blank=True, default=False, verbose_name='Buyurtma tolov statusi')),
                ('cencel', models.BooleanField(blank=True, default=False, verbose_name='Buyurtma bekor qilinganmi')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.paymentmethod', verbose_name="Qanday to'lov qilish")),
                ('punkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manzil', to='settings.dokon', verbose_name=' Yetkazib beriladigan dokon Manzil')),
                ('shahar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar', verbose_name='Shahar')),
                ('tolov_usullar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tolovusullar', verbose_name="To'lov usullari")),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tumanlar', verbose_name='Tuman')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma Bergan Foydalanuvchi')),
                ('order_items', models.ManyToManyField(blank=True, to='ordersts.orderitem', verbose_name='Savdo qilingan mahsulotlar')),
                ('vazvrat_product', models.ManyToManyField(blank=True, to='ordersts.vazvratprodcut', verbose_name='Qaytarilgan Mahsulotlar')),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at', 'zakas_id'],
            },
        ),
    ]
