# Generated by Django 5.1 on 2024-09-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
