# Generated by Django 5.0.6 on 2024-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='ordersts.orderitem', verbose_name='Savdo qilingan mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vazvrat_product',
            field=models.ManyToManyField(blank=True, to='ordersts.vazvratprodcut', verbose_name='Qaytarilgan Mahsulotlar'),
        ),
    ]
