# Generated by Django 5.0.6 on 2024-08-22 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0001_initial'),
        ('xodimlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dastafka_summa',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dastafka summasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='teskor_buyurtma_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teskor buyurtma vaqt'),
        ),
        migrations.AddField(
            model_name='order',
            name='xodim',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xodimlar.xodim', verbose_name='Xodim'),
        ),
        migrations.CreateModel(
            name='FirmaBuyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(blank=True, max_length=255, verbose_name='Firma nomi')),
                ('buyurtma_raqami', models.IntegerField(blank=True, unique=True, verbose_name='Buyurtma raqami')),
                ('inn_nomer', models.CharField(blank=True, max_length=12, verbose_name='INN nomer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
                ('shartnoma_file', models.FileField(blank=True, null=True, upload_to='shartnoma/', verbose_name='Sharhnoma file')),
                ('shartnoma_status', models.BooleanField(default=False, verbose_name='Sharhnoma statusi')),
                ('site_sts', models.BooleanField(blank=True, default=False, verbose_name='STS SITE')),
                ('site_rts', models.BooleanField(blank=True, default=False, verbose_name='RTS SITE')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='firma_buyurtma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersts.firmabuyurtma', verbose_name='Firma buyurtma'),
        ),
    ]
