# Generated by Django 5.0.6 on 2024-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0002_contactform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='tex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
