# Generated by Django 5.0.6 on 2024-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0002_order_dastafka_summa_order_teskor_buyurtma_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmabuyurtma',
            name='inn_nomer',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='INN nomer'),
        ),
    ]
