# Generated by Django 5.0.6 on 2024-11-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0003_alter_contactform_tex'),
        ('product', '0013_product_cash_foiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=25)),
                ('tavar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
