# Generated by Django 5.0.6 on 2024-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0003_alter_firmabuyurtma_inn_nomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='teskor_buyurtma_time',
        ),
        migrations.AddField(
            model_name='order',
            name='teskor_buyurtma',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
