# Generated by Django 5.0.6 on 2024-11-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0004_orderclick'),
        ('product', '0013_product_cash_foiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclick',
            name='tavar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
