# Generated by Django 5.0.6 on 2024-08-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0004_remove_order_teskor_buyurtma_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='zakas_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
