# Generated by Django 5.0.6 on 2024-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0005_alter_orderclick_tavar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclick',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
