# Generated by Django 5.0.6 on 2024-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0005_orderitem_zakas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mahsul0t_narxi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahsulot narxi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Buyurtma narxi'),
        ),
    ]
