# Generated by Django 5.0.6 on 2024-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0006_orderitem_mahsul0t_narxi_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_close',
            field=models.BooleanField(blank=True, default=False, verbose_name='Buyurtma Yopish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buyurtma bekor qilingan natija'),
        ),
    ]
