# Generated by Django 5.0.6 on 2024-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0007_order_order_close_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tushadigan_cash_summa',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Tushadigan cash summasi'),
        ),
    ]
