# Generated by Django 5.0.6 on 2024-08-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0008_order_tushadigan_cash_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazvratprodcut',
            name='mahsulot_narxi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahsulot narxi'),
        ),
        migrations.AddField(
            model_name='vazvratprodcut',
            name='site_rts',
            field=models.BooleanField(blank=True, default=True, verbose_name='RTS SITE'),
        ),
        migrations.AddField(
            model_name='vazvratprodcut',
            name='site_sts',
            field=models.BooleanField(blank=True, default=True, verbose_name='STS SITE'),
        ),
        migrations.AddField(
            model_name='vazvratprodcut',
            name='zakas_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buyurtma raqami'),
        ),
    ]
