# Generated by Django 5.0.6 on 2024-08-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0009_vazvratprodcut_mahsulot_narxi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', "Yig'ilyapti"), ('processing', 'Yetkazilyapti'), ('shipped', 'Yetkazildi'), ('delivered', 'Xaridorga berildi'), ('cencel', 'Bekor Qilindi')], default='pending', max_length=10, verbose_name='Buyurtma statusi'),
        ),
    ]
