# Generated by Django 5.1 on 2024-09-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_maincategory_created_and_more'),
        ('ordersts', '0010_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('summa', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_summa', models.PositiveBigIntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt')),
                ('barcha_tavarlar', models.BooleanField(blank=True, default=False)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.maincategory')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupon', to='ordersts.cupon')),
            ],
        ),
    ]
