# Generated by Django 5.1 on 2024-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0011_cupon_categoryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='end_at',
        ),
        migrations.AddField(
            model_name='cupon',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cupon',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
