# Generated by Django 5.1 on 2024-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0012_remove_cupon_create_at_remove_cupon_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
