# Generated by Django 5.1 on 2024-09-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersts', '0013_order_promocod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(blank=True, max_length=30)),
                ('telefon', models.CharField(blank=True, max_length=25)),
                ('tex', models.TextField(blank=True)),
            ],
        ),
    ]
