# Generated by Django 5.0.6 on 2024-08-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('settings', '0012_tolovusullar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tolov_usullar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tolovusullar'),
        ),
        migrations.AddField(
            model_name='order',
            name='yetkazish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
