# Generated by Django 5.0.6 on 2024-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
