# Generated by Django 5.0.6 on 2024-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'zakas_id'], 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk', 'created_at'], 'verbose_name_plural': 'Savdo qilingan mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='vazvratprodcut',
            options={'ordering': ['pk', 'created_at'], 'verbose_name_plural': 'Vazvrat qilingan mahsulotlar'},
        ),
    ]
