# Generated by Django 5.0.6 on 2024-08-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_testmodeluser'),
        ('settings', '0013_shaharlar_alter_cardgril_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addres',
        ),
        migrations.AddField(
            model_name='order',
            name='qishloq',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shahar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar'),
        ),
        migrations.AddField(
            model_name='order',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tumanlar'),
        ),
        migrations.AddField(
            model_name='order',
            name='uy_nomer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cashback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='depozit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='zakas_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
