# Generated by Django 5.0.6 on 2024-08-21 11:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price_alter_orderitem_product_and_more'),
        ('product', '0011_alter_product_options'),
        ('settings', '0013_shaharlar_alter_cardgril_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashback',
            field=models.FloatField(blank=True, null=True, verbose_name='Cashback  yechgan summa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cencel',
            field=models.BooleanField(blank=True, default=False, verbose_name='Buyurtma bekor qilinganmi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, null=True, verbose_name='Buyurtma uchun admin  xabarlari'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='depozit',
            field=models.FloatField(blank=True, null=True, verbose_name='Depozit yechgan summasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, verbose_name='Buyurtma tolov statusi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='orders.orderitem', verbose_name='Savdo qilingan mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.paymentmethod', verbose_name="Qanday to'lov qilish"),
        ),
        migrations.AlterField(
            model_name='order',
            name='punkit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manzil', to='settings.dokon', verbose_name=' Yetkazib beriladigan dokon Manzil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qishloq',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qishloq'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shahar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.shaharlar', verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='site_rts',
            field=models.BooleanField(blank=True, default=False, verbose_name='RTS SITE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='site_sts',
            field=models.BooleanField(blank=True, default=False, verbose_name='STS SITE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', "Yig'ilyapti"), ('processing', 'Yetkazilyapti'), ('shipped', 'Yetkazildi'), ('delivered', 'Xaridorga berildi')], default='pending', max_length=10, verbose_name='Buyurtma statusi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tolov_usullar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tolovusullar', verbose_name="To'lov usullari"),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Buyurtma narxi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tumanlar', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma Bergan Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uy_nomer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Uy nomer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vazvrat_product',
            field=models.ManyToManyField(blank=True, to='orders.vazvratprodcut', verbose_name='Qaytarilgan Mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='yetkazish',
            field=models.DateField(blank=True, null=True, verbose_name='Yetkazish sanasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zakas_id',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Buyurtma raqami'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='serena',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Mahsulot serena nomerlari'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='site_rts',
            field=models.BooleanField(blank=True, default=True, verbose_name='RTS SITE'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='site_sts',
            field=models.BooleanField(blank=True, default=True, verbose_name='STS SITE'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='vazvratprodcut',
            name='counts',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='vazvratprodcut',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Savdo qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='vazvratprodcut',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Mahsulot ID'),
        ),
        migrations.AlterField(
            model_name='vazvratprodcut',
            name='serena',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Mahsulot serena nomerlar'),
        ),
        migrations.AlterField(
            model_name='vazvratprodcut',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='vazvratprodcut',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
